// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYT2MGGh2VWLIPZNSX07qGUEWmwERiiBo',
    appId: '1:513799195868:web:df53065a76e218c530b819',
    messagingSenderId: '513799195868',
    projectId: 'safeguard-ff984',
    authDomain: 'safeguard-ff984.firebaseapp.com',
    storageBucket: 'safeguard-ff984.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3rAIe5R6HyMdfVUUMovzcQtQfxjML4Jo',
    appId: '1:513799195868:android:c180205e83e3c64e30b819',
    messagingSenderId: '513799195868',
    projectId: 'safeguard-ff984',
    storageBucket: 'safeguard-ff984.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm0NQ3p0ABswLvRDVrTWU7cUNEPtoGjHo',
    appId: '1:513799195868:ios:eeb27776a732fdfa30b819',
    messagingSenderId: '513799195868',
    projectId: 'safeguard-ff984',
    storageBucket: 'safeguard-ff984.firebasestorage.app',
    iosBundleId: 'com.safeguard.safeguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm0NQ3p0ABswLvRDVrTWU7cUNEPtoGjHo',
    appId: '1:513799195868:ios:eeb27776a732fdfa30b819',
    messagingSenderId: '513799195868',
    projectId: 'safeguard-ff984',
    storageBucket: 'safeguard-ff984.firebasestorage.app',
    iosBundleId: 'com.safeguard.safeguard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYT2MGGh2VWLIPZNSX07qGUEWmwERiiBo',
    appId: '1:513799195868:web:4446af01646e809e30b819',
    messagingSenderId: '513799195868',
    projectId: 'safeguard-ff984',
    authDomain: 'safeguard-ff984.firebaseapp.com',
    storageBucket: 'safeguard-ff984.firebasestorage.app',
  );
}
